"""Regenerate tools/model_manifest.json from the Hugging Face API at the pinned revisions.

    .venv/Scripts/python.exe tools/update_manifest.py [--check] [--endpoint https://mirror.example]

Run it after changing a pinned revision in tools/download_models.py. For every file the app needs (the same
files download_models.py fetches) it records the size and one content hash:
  - weights (Git LFS):  sha256   (the LFS object id)
  - everything else:    git_sha1 (the git blob id: sha1 of "blob <size>\\0<content>")
so `download_models.py --verify` / `doctor.py --verify-models` can prove the whole folder matches the revision.
--check compares the shipped manifest with the API instead of writing, and exits 1 when they differ.
"""
from __future__ import annotations

import argparse
import fnmatch
import json
import os
import sys
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
try:
    sys.stdout.reconfigure(encoding='utf-8')
except AttributeError:
    pass

import download_models                                                   # noqa: E402  (tools/ is sys.path[0])
import modelcheck                                                        # noqa: E402

HOW = ('Generated by tools/update_manifest.py from https://huggingface.co/api/models/<repo>/revision/<sha>?blobs=true '
       '(only the files the app needs; README/.gitattributes/examples excluded). Each file has its size and one hash: '
       'sha256 (Git LFS object id) for the weights, git_sha1 (git blob id) for everything else.')


def wanted(name: str) -> bool:
    return not any(fnmatch.fnmatch(name, pattern) for pattern in download_models.IGNORE)


def fetch_files(repo: str, revision: str, endpoint: str) -> dict[str, dict]:
    url = f'{endpoint.rstrip("/")}/api/models/{repo}/revision/{revision}?blobs=true'
    with urllib.request.urlopen(url, timeout=30) as response:
        siblings = json.load(response)['siblings']
    files: dict[str, dict] = {}
    for item in sorted(siblings, key=lambda s: s['rfilename']):
        name = item['rfilename']
        if not wanted(name):
            continue
        lfs = item.get('lfs')
        files[name] = {'size': item['size'],
                       'sha256': lfs['sha256'] if lfs else None,
                       'git_sha1': None if lfs else item['blobId']}
    return files


def build(endpoint: str) -> dict:
    models = {}
    for model in download_models.MODELS.values():
        models[model.repo] = {'revision': model.revision, 'files': fetch_files(model.repo, model.revision, endpoint)}
    return {'_how': HOW, 'models': models}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--check', action='store_true', help='compare with the shipped manifest; write nothing')
    parser.add_argument('--endpoint', default=os.environ.get('HF_ENDPOINT', 'https://huggingface.co'))
    args = parser.parse_args()
    fresh = build(args.endpoint)
    if args.check:
        shipped = modelcheck.load_manifest()
        if shipped.get('models') == fresh['models']:
            print('model_manifest.json 與 Hugging Face 上固定版本的內容相符。')
            return 0
        print('model_manifest.json 與 Hugging Face 上固定版本不同，請執行 tools/update_manifest.py 重新產生。', file=sys.stderr)
        return 1
    modelcheck.MANIFEST_PATH.write_text(json.dumps(fresh, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    for repo, spec in fresh['models'].items():
        print(f'{repo}@{spec["revision"][:8]}：{len(spec["files"])} 個檔案')
    print(f'已寫入 {modelcheck.MANIFEST_PATH}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
